version: '3'

services:
    migration:
        build: .
        command: python3 wander/manage.py migrate
        volumes:
            - .:/usr/src/app
    web:
        build: .
        command: python3 wander/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - migration
