# Generated by Django 2.0.3 on 2019-05-04 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=10)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(default=None)),
                ('rate', models.IntegerField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ManyToManyField(related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy', models.CharField(default='public', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
