# Generated by Django 2.0.3 on 2019-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wanderapp', '0002_auto_20190504_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='rate',
        ),
    ]
